package com.pokemonaddon.api.model;

public enum ItemType {

	BERRY,
	COLORED_ORB,
	DRIVE,
	EV_ENCHANCING_ITEM,
	EVOLUTION_INDUCING_HELD_ITEM,
	EXPERIENCE_AFFETING_ITEM,
	GEM,
	INCENSE,
	MEGA_STONE,
	MEMORY,
	PLATE,
	STAT_ENHANCING_ITEM,
	TYPE_ENHANCING_ITEM,
	Z_CRYSTAL,
	IN_BATTLE_EFFECT_ITEM,
	OUT_OF_BATTLE_EFFECT_ITEM,
	MAIL,
	SCARVE
}
